---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ShizheChang.
--- DateTime: 2024/3/22 16:23
---
DownloadURL = "https://github.com/JetBrains/kotlin/releases/download/v%s/kotlin-compiler-%s.zip"
KOTLIN_RELEASE_URL = "https://kotlinlang.org/docs/releases.html#release-details"